# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/justdecompile"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock]
exclude_navigation: ["knowledge-base/*"]

navigation:
## List your directory names and order here, like this:

    plugin-basics:
        title: Plugin Basics
        position: 1

    ui-regions:
        title: UI Regions
        position: 2

    events:
        title: Events
        position: 3

    services:
        title: Services
        position: 4
      
    "knowledge-base":
        title: "Knowledge Base"
        isNew: true
        position: 5

## The application virtual path
baseurl: /devtools/justdecompile


## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "justdecompile"
-
    scope:
        path: "knowledge-base"
    values:
        res_type: "kb"
        
# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

ff-sheet-id: 9dbd70b3-b986-4bd1-af83-2aae0115d2ff
product: "Telerik JustDecompile"
platform: "justdecompile"
has_kb_portal: true
api_reference_url: "api/"

edit_repo_url: https://github.com/telerik/justdecompile-docs/edit/master
download: http://www.telerik.com/download-trial-file/v2/justdecompile
nav:
  "Features": https://www.telerik.com/products/decompiler.aspx#Features
  "Whats new": https://www.telerik.com/support/whats-new/justdecompile
  "About": https://www.telerik.com/products/decompiler

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:ptty4k2yaka'
gcs_api_key: 'AIzaSyCCJ8KxA6_2GV3IngVPL8VRGr2GGOKorc4'

footer:
-
  title: "Getting Started"
  links:
    "FAQs": https://www.telerik.com/products/decompiler/faq.aspx
    "Videos": https://www.telerik.com/videos/justdecompile
    "Whats new": https://www.telerik.com/support/whats-new/justdecompile
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/justdecompile
    "Blogs": https://www.telerik.com/blogs/.net
    "User Voice": http://justdecompile.uservoice.com/forums/113277-justdecompile-feature-suggestions
-
  title: "Resources"
  links:
    "Extensions": https://www.telerik.com/products/decompiler/extensions.aspx
    "Features": https://www.telerik.com/products/decompiler.aspx#Features

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
