# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/justdecompile"

# Exclude files which should not be in the output
exclude: [readme.md, Gemfile, Gemfile.lock,api_sort.rb]
navigation:
## List your directory names and order here, like this:

    plugin-basics:
        title: Plugin Basics
        position: 1

    ui-regions:
        title: UI Regions
        position: 2

    events:
        title: Events
        position: 3

    services:
        title: Services
        position: 4
      
    "knowledge-base":
        title: "Knowledge Base"
        isNew: true
        position: 5

## The application virtual path
baseurl: /devtools/justdecompile


## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "justdecompile"
        editable: false
-
    scope:
        path: "knowledge-base"
    values:
        layout: "kb-page"
        
## The Kendo UI version used
cdnVersion: "2017.3.1026"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

ff-sheet-id: 9dbd70b3-b986-4bd1-af83-2aae0115d2ff

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:ptty4k2yaka'
google_custom_kb_search: '001595215763381649090:nu6xgdkotlc'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
